"""Add about_me and last_seen to User

Revision ID: 031698916dff
Revises: 612f0d138ac8
Create Date: 2020-01-02 13:23:02.714866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031698916dff'
down_revision = '612f0d138ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
